### ISSUE TITLE
recompile with GLIBC 3.4.14 to increase backwards compatibility 

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/EpochServer#6]
https://epochmod.com/forum/topic/42933-epochserverso-compiled-with-much-newer-version-of-glibc-killing-centos-7-compatibility/

**Comment by vbawol** [comment]
@xai1 are you still running a Linux Epoch server? If so I have some new extensions to test out. These are build using holy build box and should be compatible with a wider range of distros.

32bit Linux:
https://github.com/EpochModTeam/Epoch/blob/6b4f6ed0cbe188a74796b09a66ed416db619930f/Server_Install_Pack/@epochhive/epochserver.so?raw=true
64bit Linux:
https://github.com/EpochModTeam/Epoch/blob/6b4f6ed0cbe188a74796b09a66ed416db619930f/Server_Install_Pack/@epochhive/epochserver_x64.so?raw=true

These binaries should work on pretty much any glibc-based x86 and x86-64 Linux distribution released in the last ten years.

Debian >= 6
Ubuntu >= 10.04
Red Hat Enterprise Linux >= 5
CentOS >= 5

**Comment by xai1** [comment]
@vbawol thanks for info. I am not running an Epoch server on Linux at the moment. But I can install one and give it a try if you need help with testing?

**Comment by vbawol** [comment]
@xai1 Sure if you have time that would be great. Last time I attempted to setup an A3 Linux server I could never get it to work. I think I will see about using a docker based install to test it here in the next few days, that way I won't have to bother others to confirm these builds.

**Comment by vbawol** [comment]
Just updated again and I was able to confirm the latest x86 build does work and that is now statically linked to hiredis and pcre. If it does not work for you please let me know.

https://github.com/EpochModTeam/Epoch/blob/experimental/Server_Install_Pack/@epochhive/epochserver.so?raw=true

**Comment by xai1** [comment]
@vbawol sry hadn't been able to test anything. If you need anyone to test sth in the future feel free to contact me.
